from peewee import *
from config import DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT

db = PostgresqlDatabase(database=DB_NAME, user=DB_USER, password=DB_PASSWORD, host=DB_HOST, port=DB_PORT)

class BaseModel(Model):
    """A base model that will use our Postgresql database"""
    class Meta:
        database = db

class BanList(BaseModel):
    id = BigAutoField(primary_key=True)  # bigint generated by default as identity
    created_at = TimestampField(constraints=[SQL('DEFAULT now()')])  # timestamp with time zone
    user_id = BigIntegerField(null=True)  # bigint, nullable
    ban_start = TimestampField(null=False)  # timestamp without time zone
    ban_end = TimestampField(null=False)  # timestamp without time zone
    reason = TextField(null=False)  # text, not nullable
    ban_from = TextField(null=False)  # text, not nullable

    class Meta:
        table_name = 'ban_list'

class BotStatus(BaseModel):
    id = BigAutoField(primary_key=True)  # bigint generated by default as identity
    created_at = TimestampField(constraints=[SQL('DEFAULT now()')])  # timestamp with time zone, default now()
    up_time = TimestampField(null=False)  # timestamp without time zone
    down_time = TimestampField(null=False)  # timestamp without time zone

    class Meta:
        table_name = 'bot_status'

class TextModel(BaseModel):
    id = BigAutoField(primary_key=True)  # bigint generated by default as identity
    edited_at = TimestampField(null=True)  # timestamp without time zone, nullable
    target = TextField(null=False)  # text, not nullable
    text_of = TextField(null=False)  # text, not nullable

    class Meta:
        table_name = 'text'