from peewee import *
from config import DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT

db = PostgresqlDatabase(database=DB_NAME, user=DB_USER, password=DB_PASSWORD, host=DB_HOST, port=DB_PORT)

class BaseModel(Model):
    class Meta:
        database = db

class BanList(BaseModel):
    id = BigAutoField(primary_key=True)  # bigint generated by default as identity
    created_at = TimestampField(constraints=[SQL('DEFAULT now()')])  # timestamp with time zone
    user_id = BigIntegerField(null=True)  # bigint, nullable
    ban_start = TimestampField(null=False)  # timestamp without time zone
    ban_end = TimestampField(null=False)  # timestamp without time zone
    reason = TextField(null=False)  # text, not nullable
    ban_from = TextField(null=False)  # text, not nullable

    class Meta:
        table_name = 'ban_list'

class TextModel(BaseModel):
    id = BigAutoField(primary_key=True)  # bigint generated by default as identity
    edited_at = TimestampField(null=True)  # timestamp without time zone, nullable
    target = TextField(null=False)  # text, not nullable
    text_of = TextField(null=False)  # text, not nullable

    class Meta:
        table_name = 'text'

class AnekModel(BaseModel):
    id = BigAutoField(primary_key=True)
    created_at = TimestampField(constraints=[SQL('DEFAULT now()')])
    user_id = BigIntegerField(null=False,unique=True)
    count = BigIntegerField(default=0)

    class Meta:
        table_name = 'anek_list'

class User_listModel(BaseModel):
    id = BigAutoField(primary_key=True)
    created_at = TimestampField(constraints=[SQL('DEFAULT now()')])
    user_id = BigIntegerField(null=False,unique=True)
    message_count = BigIntegerField(default=0)

    class Meta:
        table_name = 'user_list'

class Chat_listModel(BaseModel):
    id = BigAutoField(primary_key=True)
    created_at = TimestampField(constraints=[SQL('DEFAULT now()')])
    chat_id = BigIntegerField(null=False,unique=True)

    class Meta:
        table_name = 'chat_list'

class Button_listModel(BaseModel):
    id = BigAutoField(primary_key=True)  # bigint generated by default as identity
    button_name = TextField(null=False)  # text, not nullable
    button_link = TextField(null=False)  # text, not nullable

    class Meta:
        table_name = 'button_list'

class SizeModel(BaseModel):
    id = BigAutoField(primary_key=True)
    user_id = BigIntegerField(null=False, unique=True)
    size = IntegerField(null=False)
    date = DateField(null=False)  # The date the size was set

    class Meta:
        table_name = 'size_list'